# -*- coding: utf-8 -*-
"""DATA VISUALIZATION DASHBOARD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srsHkYOU46lczqJQ7VWB4S6vQH43huIK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset("iris")
print(df.to_string())

df.head()

import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset("iris")
sns.set(style="whitegrid")
plt.figure(figsize=(6,4))
sns.countplot(x='species',data=df,palette="pastel")
plt.title("Distribution of Iris Species",fontsize=18)
plt.xlabel("Species",fontsize=14)
plt.ylabel("Count",fontsize=14)
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(x="species",y="petal_length",data=df,palette="bright")
plt.title("Petal length distribution by species",fontsize=18)
plt.xlabel("species",fontsize=14)
plt.ylabel("petal_length",fontsize=14)
plt.show()

plt.figure(figsize=(6,4))
sns.scatterplot(x="petal_length",y="petal_width",data=df,palette="dark")
plt.title("Petal length and width distribution by species",fontsize=18)
plt.xlabel("petal_length",fontsize=14)
plt.ylabel("petal_width",fontsize=14)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df['species'] = [iris.target_names[i] for i in iris.target]

total_samples = len(df)
avg_sepal_length = df['sepal_length'].mean()
avg_sepal_width = df['sepal_width'].mean()
max_petal_length = df['petal_length'].max()
species_count = df['species'].value_counts().to_dict()

sns.set_style("darkgrid")

fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(20, 6))
fig.patch.set_facecolor('#0f1116')
plt.subplots_adjust(top=0.8, wspace=0.3)

for ax in axes:
    ax.set_facecolor('#1b1f27')
    ax.tick_params(colors='white')
    ax.xaxis.label.set_color('white')
    ax.yaxis.label.set_color('white')
    ax.title.set_color('#f5b041')
    ax.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.4)

plt.suptitle('Iris Dataset Dashboard', fontsize=24, fontweight='bold', y=0.98, color='#f8f9f9')

sns.scatterplot(x="petal_length", y="petal_width", hue="species", data=df,
                palette="viridis", s=100, ax=axes[0])
axes[0].set_title("Petal Length vs Width by Species", fontsize=14, fontweight='bold')

sns.boxplot(x="species", y="petal_length", hue="species", data=df,
            palette="cool", ax=axes[1], legend=False)
axes[1].set_title("Petal Length Distribution by Species", fontsize=14, fontweight='bold')

sns.countplot(x='species', hue='species', data=df, palette="mako", ax=axes[2], legend=False)
axes[2].set_title("Distribution of Iris Species", fontsize=14, fontweight='bold')

kpi_text = (f'Total Samples: {total_samples}    |    '
            f'Avg Sepal Length: {avg_sepal_length:.2f}    |    '
            f'Avg Sepal Width: {avg_sepal_width:.2f}    |    '
            f'Max Petal Length: {max_petal_length:.2f}    |    '
            f'Species Count: {species_count}')
fig.text(0.5, 0.91, kpi_text, ha='center', va='center',
         fontsize=12, fontweight='bold', color='#AED6F1')

plt.tight_layout(rect=[0, 0, 1, 0.88])
plt.show()